### PR TITLE
Added Dockerfile and context in the Readme

### PR DESCRIPTION
**Pull request by kamackay**

### CODE REVIEW

**Comment by kamackay** [comment]
With this, if you want, we could host it up on hub.docker.com under your username and whenever you commit to it, the image would automatically rebuild

**Comment by trishmapow** [comment]
Cool, I haven't really used Docker before but I'll have a look

**Comment by trishmapow** [comment]
Ok I think this is right? https://hub.docker.com/r/trishmapow/nordvpn-tools

**Comment by kamackay** [comment]
Yeah, looks right. I'll update the readme so that people know they don't need to build

**Comment by kamackay** [comment]
Sweet yeah that built!

**Comment by trishmapow** [comment]
Nice, much easier than I thought! btw shouldn't it be python3 in the dockerfile, it's not really python2 compatible right now

**Comment by kamackay** [comment]
That image that's pulled should only have python3, but be referring to it as just `python`. One second, let me check

**Comment by kamackay** [comment]
Yeah it's python is 3.7.4

**Pull request merged**
